name: Library-Catalog CI/CD

on:
  push:
    branches: []
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Node modules 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Start the app
        run: npm run start-frontend & npm run start-backend        
      - name: Wait for app start  
        run: sleep 10
      - name: Run the tests
        run: npm run playwright
